export {default as Magnifier} from './Magnifier';
export {default as Copy} from './Copy';
export {default as HeadAbove} from './pages/HeadAbove';
export {default as HeadAndNeckHandAbove} from './pages/HeadAndNeckHandAbove';
export {default as HeadAndNeckAbove} from './pages/HeadAndNeckAbove';
export {default as HeadAndFootAbove} from './pages/HeadAndFootAbove';
export {default as LegsUp} from './pages/LegsUp'
export {default as Dive} from './pages/Dive';
export {default as TailsAbove} from './pages/TailsAbove';
export {default as Arrow} from './Arrow';
export {default as Ears} from './pages/Ears';