export type URLS_CONFIG_TYPE = {
  TRANSACTION_DETAILS_URL: string;
  BLOCK_DETAILS_URL: string;
  GO_CORE_CLIENT_URL: string;
  CORE_TALK_SPACE_URL: string;
  ICAN_WALLET_URL: string;
  GITHUB_RELEASE_DOWNLOAD_URL: string;
  GITHUB_RAW_MINE_SH: string;
};

export type POOLS_API_CONFIG_TYPE = Record<
  | "EU_PRIMARY_API_ENDPOINT"
  | "NEXT_PUBLIC_EU_PRIMARY_API_ENDPOINT"
  | "EU_BACKUP_API_ENDPOINT"
  | "NEXT_PUBLIC_EU_BACKUP_API_ENDPOINT"
  | "AS_PRIMARY_API_ENDPOINT"
  | "NEXT_PUBLIC_AS_PRIMARY_API_ENDPOINT"
  | "AS_BACKUP_API_ENDPOINT"
  | "NEXT_PUBLIC_AS_BACKUP_API_ENDPOINT"
  | "US_PRIMARY_API_ENDPOINT"
  | "NEXT_PUBLIC_US_PRIMARY_API_ENDPOINT"
  | "US_BACKUP_API_ENDPOINT"
  | "NEXT_PUBLIC_US_BACKUP_API_ENDPOINT",
  string
>;

export type START_MINING_POOL_CONFIGURATIONS = Record<
  | "EU_FULL_NAME"
  | "EU_NAME"
  | "EU_SERVER"
  | "EU_PORT"
  | "EU_USERNAME"
  | "EU_PASSWORD"
  | "EU_BACKUP_FULL_NAME"
  | "EU_BACKUP_NAME"
  | "EU_BACKUP_SERVER"
  | "EU_BACKUP_PORT"
  | "EU_BACKUP_USERNAME"
  | "EU_BACKUP_PASSWORD"
  | "AS_FULL_NAME"
  | "AS_NAME"
  | "AS_SERVER"
  | "AS_PORT"
  | "AS_USERNAME"
  | "AS_PASSWORD"
  | "AS_BACKUP_FULL_NAME"
  | "AS_BACKUP_NAME"
  | "AS_BACKUP_SERVER"
  | "AS_BACKUP_PORT"
  | "AS_BACKUP_USERNAME"
  | "AS_BACKUP_PASSWORD"
  | "US_FULL_NAME"
  | "US_NAME"
  | "US_SERVER"
  | "US_PORT"
  | "US_USERNAME"
  | "US_PASSWORD"
  | "US_BACKUP_FULL_NAME"
  | "US_BACKUP_NAME"
  | "US_BACKUP_SERVER"
  | "US_BACKUP_PORT"
  | "US_BACKUP_USERNAME"
  | "US_BACKUP_PASSWORD",
  string
>;
