// All supported currencies ordered by name (alphabetically)
export const currencies = [
  { value: 'AED', name: 'UAE Dirham' },
  { value: 'ARS', name: 'Argentine Peso' },
  { value: 'AUD', name: 'Australian Dollar' },
  { value: 'AZN', name: 'Azerbaijani Manat' },
  { value: 'BBD', name: 'Barbadian Dollar' },
  { value: 'BDT', name: 'Bangladeshi Taka' },
  { value: 'BGN', name: 'Bulgarian Lev' },
  { value: 'BHD', name: 'Bahraini Dinar' },
  { value: 'BIF', name: 'Burundian Franc' },
  { value: 'BOB', name: 'Bolivian Boliviano' },
  { value: 'BRL', name: 'Brazilian Real' },
  { value: 'BSD', name: 'Bahamian Dollar' },
  { value: 'BWP', name: 'Botswana Pula' },
  { value: 'CAD', name: 'Canadian Dollar' },
  { value: 'CHF', name: 'Swiss Franc' },
  { value: 'CLP', name: 'Chilean Peso' },
  { value: 'CNY', name: 'Chinese Yuan' },
  { value: 'COP', name: 'Colombian Peso' },
  { value: 'CRC', name: 'Costa Rican Colón' },
  { value: 'CUP', name: 'Cuban Peso' },
  { value: 'CZK', name: 'Czech Koruna' },
  { value: 'DKK', name: 'Danish Krone' },
  { value: 'DOP', name: 'Dominican Peso' },
  { value: 'EGP', name: 'Egyptian Pound' },
  { value: 'ETB', name: 'Ethiopian Birr' },
  { value: 'EUR', name: 'Euro' },
  { value: 'GBP', name: 'British Pound' },
  { value: 'GHS', name: 'Ghanaian Cedi' },
  { value: 'GNF', name: 'Guinean Franc' },
  { value: 'GTQ', name: 'Guatemalan Quetzal' },
  { value: 'HKD', name: 'Hong Kong Dollar' },
  { value: 'HNL', name: 'Honduran Lempira' },
  { value: 'HTG', name: 'Haitian Gourde' },
  { value: 'HUF', name: 'Hungarian Forint' },
  { value: 'IDR', name: 'Indonesian Rupiah' },
  { value: 'ILS', name: 'Israeli Shekel' },
  { value: 'INR', name: 'Indian Rupee' },
  { value: 'IQD', name: 'Iraqi Dinar' },
  { value: 'ISK', name: 'Icelandic Króna' },
  { value: 'JMD', name: 'Jamaican Dollar' },
  { value: 'JOD', name: 'Jordanian Dinar' },
  { value: 'JPY', name: 'Japanese Yen' },
  { value: 'KES', name: 'Kenyan Shilling' },
  { value: 'KGS', name: 'Kyrgyzstani Som' },
  { value: 'KHR', name: 'Cambodian Riel' },
  { value: 'KRW', name: 'South Korean Won' },
  { value: 'KWD', name: 'Kuwaiti Dinar' },
  { value: 'KZT', name: 'Kazakhstani Tenge' },
  { value: 'LAK', name: 'Lao Kip' },
  { value: 'LBP', name: 'Lebanese Pound' },
  { value: 'LYD', name: 'Libyan Dinar' },
  { value: 'MAD', name: 'Moroccan Dirham' },
  { value: 'MDL', name: 'Moldovan Leu' },
  { value: 'MGA', name: 'Malagasy Ariary' },
  { value: 'MKD', name: 'Macedonian Denar' },
  { value: 'MMK', name: 'Myanmar Kyat' },
  { value: 'MOP', name: 'Macanese Pataca' },
  { value: 'MUR', name: 'Mauritian Rupee' },
  { value: 'MVR', name: 'Maldivian Rufiyaa' },
  { value: 'MWK', name: 'Malawian Kwacha' },
  { value: 'MXN', name: 'Mexican Peso' },
  { value: 'MYR', name: 'Malaysian Ringgit' },
  { value: 'MZN', name: 'Mozambican Metical' },
  { value: 'NAD', name: 'Namibian Dollar' },
  { value: 'NGN', name: 'Nigerian Naira' },
  { value: 'NIO', name: 'Nicaraguan Córdoba' },
  { value: 'NOK', name: 'Norwegian Krone' },
  { value: 'NPR', name: 'Nepalese Rupee' },
  { value: 'NZD', name: 'New Zealand Dollar' },
  { value: 'OMR', name: 'Omani Rial' },
  { value: 'PEN', name: 'Peruvian Sol' },
  { value: 'PHP', name: 'Philippine Peso' },
  { value: 'PKR', name: 'Pakistani Rupee' },
  { value: 'PLN', name: 'Polish Złoty' },
  { value: 'PYG', name: 'Paraguayan Guaraní' },
  { value: 'QAR', name: 'Qatari Riyal' },
  { value: 'RON', name: 'Romanian Leu' },
  { value: 'RSD', name: 'Serbian Dinar' },
  { value: 'RUB', name: 'Russian Ruble' },
  { value: 'RWF', name: 'Rwandan Franc' },
  { value: 'SAR', name: 'Saudi Riyal' },
  { value: 'SCR', name: 'Seychellois Rupee' },
  { value: 'SDG', name: 'Sudanese Pound' },
  { value: 'SEK', name: 'Swedish Krona' },
  { value: 'SGD', name: 'Singapore Dollar' },
  { value: 'SOS', name: 'Somali Shilling' },
  { value: 'THB', name: 'Thai Baht' },
  { value: 'TJS', name: 'Tajikistani Somoni' },
  { value: 'TND', name: 'Tunisian Dinar' },
  { value: 'TRY', name: 'Turkish Lira' },
  { value: 'TWD', name: 'New Taiwan Dollar' },
  { value: 'TZS', name: 'Tanzanian Shilling' },
  { value: 'UAH', name: 'Ukrainian Hryvnia' },
  { value: 'UGX', name: 'Ugandan Shilling' },
  { value: 'USD', name: 'United States Dollar' },
  { value: 'UYU', name: 'Uruguayan Peso' },
  { value: 'UZS', name: 'Uzbekistani Som' },
  { value: 'VND', name: 'Vietnamese Đồng' },
  { value: 'XAF', name: 'Central African CFA Franc' },
  { value: 'XOF', name: 'West African CFA Franc' },
  { value: 'XPF', name: 'CFP Franc' },
  { value: 'YER', name: 'Yemeni Rial' },
  { value: 'ZAR', name: 'South African Rand' },
  { value: 'ZMW', name: 'Zambian Kwacha' }
];

// Top currencies
export const topCurrencies = [
  { value: 'EUR', name: 'Euro' },
  { value: 'USD', name: 'US Dollar' },
  { value: 'CHF', name: 'Swiss Franc' }
];
