name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!
  - type: dropdown
    id: component
    attributes:
      label: Component Category
      description: Which component category would this feature affect?
      options:
        - Atoms
        - Molecules
        - Organisms
        - Templates
        - Pages
        - Hooks
        - Utils
        - API
        - Theme
        - New Component
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Describe the problem this feature would solve
      placeholder: What problem are you trying to solve?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution
      placeholder: How would you like this feature to work?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions you've considered
      placeholder: What other approaches have you considered?
  - type: textarea
    id: mockups
    attributes:
      label: Mockups
      description: If applicable, add mockups or screenshots to help explain your feature
      placeholder: Add mockups or screenshots here
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - High - This is blocking my work
        - Medium - This would be nice to have
        - Low - This is a nice-to-have feature
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the feature request here
      placeholder: Any additional information that might be relevant
